version: '3.8'

services:
  # Development service
  radio-russell-dev:
    build:
      context: .
      target: development
    container_name: radio-russell-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - radio-russell-data-dev:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_PATH=/app/data/database.db
    restart: unless-stopped
    networks:
      - radio-russell-network
    profiles:
      - dev

  # Production service
  radio-russell-prod:
    build:
      context: .
      target: production
    container_name: radio-russell-prod
    ports:
      - "8000:8000"
    volumes:
      - radio-russell-data-prod:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_PATH=/app/data/database.db
    restart: always
    networks:
      - radio-russell-network
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/users"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy for production (nginx)
  nginx:
    image: nginx:alpine
    container_name: radio-russell-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - radio-russell-prod
    networks:
      - radio-russell-network
    profiles:
      - prod
      - nginx
    restart: always

volumes:
  radio-russell-data-dev:
    driver: local
  radio-russell-data-prod:
    driver: local

networks:
  radio-russell-network:
    driver: bridge
